config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def update
    @flat = Flat.find(params[:id])
    if @flat.update(flat_params)
      redirect_to flat_path(@flat)
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :number_of_guests, :price_per_night )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_card.html.erb
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <%= link_to flat_path(flat), class: 'text-decoration-none fw-lighter text-black' do %>
    <h5 class="card-title"><%= flat.name %></h5>
    <p class="card-text"><%= flat.description %></p>
    <div class="card-subtitle d-flex justify-content-end align-items-center">
      <span>🧑‍🤝‍🧑 <%= flat.number_of_guests %></span>
      <span>💲 <%= flat.price_per_night %></span>
    </div>
    <% end %>
  </div>
</div>

app/views/flats/index.html.erb
<div class="container mt-5">
  <div class="d-flex align-items-center">
    <h1 class="fw-bolder">All Flats</h1>
    <div class="ml-5">
      <%= link_to new_flat_path, class: 'text-dark text-decoration-none h5' do %>
          <i class="fa-solid fa-plus"></i>
      <% end %>
    </div>
  </div>
  <% @flats.each do |flat| %>
    <%= render 'flats/card', flat: flat %>
  <% end %>
</div>

app/views/flats/new.html.erb
<div class="container mt-5">
  <div class="mb-3">
    <%= link_to '< Flats', flats_path, class: 'btn-light opacity-25 text-decoration-none' %>
  </div>
  <h1>Upload a Flat</h1>
  <%= simple_form_for @flat do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :number_of_guests %>
    <%= f.input :price_per_night %>
    <%= f.submit class: 'btn btn-primary mt-3' %>
  <% end %>
</div>

app/views/flats/show.html.erb
<div class="container mt-2">
  <div class="row justify-content-around">
    <div class="col-12 col-sm-8">
      <p>
        <%= link_to '< Flats', flats_path, class: 'btn-light opacity-25 text-decoration-none' %>
      </p>
      <div class="d-flex align-items-center">
        <h1 class="md-3 fw-bold"><%= @flat.name %></h1>
      </div>
      <div class="d-flex flex-column justify-content-center align-items-center mt-2 fw-lighter opacity-75">
        <p>📍 <%= @flat.address  %></p>
        <p>✍️ <%= @flat.description  %></p>
      </div>
      <div class="d-flex flex-column align-items-end fw-lighter opacity-75;">
        <p>🧑‍🤝‍🧑 <%= @flat.number_of_guests  %></p>
        <p>💲 <%= @flat.price_per_night  %></p>
      </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>